[platformio]
default_envs = xiao_esp32s3

[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
; Uncomment and set if auto-detection fails:
; upload_port = COM3
; monitor_port = COM3
