; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = xiao_esp32s3

[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
src_filter = +<main_i2c_ssd1306_128x64_v2.cpp>
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  olikraus/U8g2@^2.36.3

[env:xiao_esp32s3_st7789_lgfx]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
src_filter = +<main_spi_st7789_320x170_lgfx_v1.cpp>
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  lovyan03/LovyanGFX@^1.2.21
