[platformio]
default_envs = xiao_esp32s3

[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
src_filter = +<main_i2c_ssd1306_128x64_v2.cpp>
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  olikraus/U8g2@^2.36.3
; Uncomment and set if auto-detection fails:
; upload_port = COM3
; monitor_port = COM3
